spring:
  redis:
    database: 0           # Redis数据库索引（默认为0）
#    host: 120.79.223.29   # 我本人的服务器，如果报错连不上，你就换成自己的redis服务器
    host: localhost
    port: 6379            # redis 的默认端口号
    password:             # 服务没有密码
    timeout: 1000         # 连接超时时间（毫秒）
    jedis:
      pool:
        max-idle: 10      # 连接池中的最大空闲连接
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0       # 连接池中的最小空闲连接


server:
  port: 8081